<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ConceptoMaestro;

class CompromisosPoaSeeder extends Seeder
{
    public function run(): void
    {
        $compromisos = [
            [
                'nombre' => 'PRESUPUESTO DE VENTA PAR',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 1,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => 'VENTAS A TIENDAS',
            ],
            [
                'nombre' => 'PRESUPUESTO DE VENTA PE',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 2,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => 'VENTAS PROGRAMAS ESPECIALES',
            ],
            [
                'nombre' => 'PRESUPUESTO DE VENTA TOTAL',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 3,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => 'VENTAS NETAS',
            ],
            [
                'nombre' => 'RESULTADO DIRECTO DE OPERACIÓN',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 4,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => 'RESULTADO DIRECTO DE OPERACIÓN',
            ],
            [
                'nombre' => 'GASTOS DE OPERACIÓN',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 5,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => 'TOTAL DE GTOS DE DISTRIBUCION',
            ],
            [
                'nombre' => 'OPORTUNIDAD DE SURTIMIENTO A TIENDAS',
                'categoria' => 'POA',
                'unidad_medida' => 'PORCENTAJE',
                'orden' => 6,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'EFICIENCIA DE SURTIMIENTO A TIENDAS',
                'categoria' => 'POA',
                'unidad_medida' => 'PORCENTAJES',
                'orden' => 7,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'MERMAS, QUEBRANTOS Y MAL ESTADO',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 8,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'APERTURA DE TIENDAS',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 9,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'APERTURA DE TIENDAS LOCALIDAD OBJETIVO',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 10,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'APERTURA DE TIENDAS LOCALIDAD ESTRATEGICA',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 11,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'REACTIVACIÓN DE TIENDAS CON ROTACIÓN CERO Y MENOR A UNA VUELTA',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 12,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'SANEAMIENTO EN TIENDAS COMUNITARIAS',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 13,
                'label_fila_1' => 'TIENDAS A SANEAR',
                'label_fila_2' => 'TIENDAS SANEADAS',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'RECUPERACIÓN DE FALTANTES DE CAPITAL DE TRABAJO DE TIENDAS',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 14,
                'label_fila_1' => 'IMPORTE A RECUPERAR',
                'label_fila_2' => 'IMPORTE RECUPERADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'CONVERSIÓN DE TIENDAS A U.S.C.',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE TIENDAS',
                'orden' => 15,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'RENOVACIÓN DE COMITES DE ABASTO',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE C.A.',
                'orden' => 16,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'RENOVACIÓN M.D. DEL C.C.A. A.C.',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO DE C.C.A.',
                'orden' => 17,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'ADECUACIÓN DE CAPITAL EN TIENDAS COMUNITARIAS',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 18,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'ADECUACIÓN DE CAPITAL INCREMENTO',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 19,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'ADECUACIÓN DE CAPITAL DECREMENTO',
                'categoria' => 'POA',
                'unidad_medida' => 'PESOS',
                'orden' => 20,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'REUNIONES DE COORDINACIÓN Y EVALUACIÓN',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO',
                'orden' => 21,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'CURSOS DE CAPACITACION A ETC Y CA',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO',
                'orden' => 22,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'PROMOCIÓN DE ASAMBLEAS COMUNITARIAS',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO',
                'orden' => 23,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'ASAMBLEAS COMUNITARIAS',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO',
                'orden' => 24,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
            [
                'nombre' => 'ASAMBLEAS DE C. C. A.C.',
                'categoria' => 'POA',
                'unidad_medida' => 'NÚMERO',
                'orden' => 25,
                'label_fila_1' => 'COMPROMETIDO',
                'label_fila_2' => 'REALIZADO',
                'concepto_er_nombre' => null,
            ],
        ];

        foreach ($compromisos as $compromiso) {
            ConceptoMaestro::updateOrCreate(
                ['nombre' => $compromiso['nombre'], 'categoria' => 'POA'],
                $compromiso
            );
        }
    }
}
